/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ren Viro Store (https://sketchfab.com/renviros)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/desk-set-f26030d09d73422f8ff270425c7c63e0
Title: Desk Set
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Desk = (props)=> {
    const group=useRef()

  // Leva kontrollü state
/*   const { position, rotation, scale } = useControls("Desk", {
    position: { value: [0, -1, 0], step: 0.1 },
    rotation: { value: [0, Math.PI, 0], step: 0.1 },
    scale: { value: 0.002, min: 0.001, max: 0.01, step: 0.001 },
  }); */
  const { nodes, materials } = useGLTF('/models/desk_set.glb')
  return (
    <group {...props} dispose={null} ref={group}       
>
      <group position={[1287.773, 786.161, 833.715]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Desk_Desk_0.geometry}
          material={materials.Desk}
        />
        <group position={[-360.062, -26.253, -77.9]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Desk-Door_02_Desk_0'].geometry}
            material={materials.Desk}
            position={[360.062, 25.21, 77.9]}
          />
        </group>
        <group position={[360.063, -34.263, -77.9]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Desk-Door_01_Desk_0'].geometry}
            material={materials.Desk}
            position={[360.062, 25.21, 77.9]}
          />
        </group>
      </group>
      <group position={[1468.742, 0, 1477.194]} rotation={[-Math.PI / 2, 0, 0.96]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Office-Chair_Office-Chair_0'].geometry}
          material={materials['Office-Chair']}
          position={[-16.848, 2.917, 461.853]}
        />
      </group>
      <group
        position={[1891.646, 1021.561, 668.308]}
        rotation={[Math.PI, -0.313, Math.PI]}
        scale={0.838}>
        <group
          position={[69.681, 160.084, 0.169]}
          rotation={[-Math.PI / 2, 0, -2.407]}
          scale={0.624}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Lamp-Decorative_03_Lamp_Decorative_0'].geometry}
            material={materials.Lamp_Decorative}
            position={[0, 0, 640.944]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Table-Lamp_Table-Lamp_0'].geometry}
          material={materials['Table-Lamp']}
          position={[21.832, 64.609, -612.305]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Photography_Type1_Photography-Type_1_0'].geometry}
        material={materials['Photography-Type_1']}
        position={[850.093, 815.947, 645.349]}
        rotation={[-0.581, 0.114, -1.496]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Book-Type1_Book-Type_1_0'].geometry}
        material={materials['Book-Type_1']}
        position={[1910.513, 817.679, 947.855]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Book-Type2_Book-Type_2_0'].geometry}
        material={materials['Book-Type_2']}
        position={[1902.696, 860.16, 947.855]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Photography_Type2_Photography-Type_2_0'].geometry}
        material={materials['Photography-Type_2']}
        position={[681.144, 921.938, 581.522]}
        rotation={[2.879, -0.059, 3.126]}
        scale={1.17}
      />
    </group>
  )
}

useGLTF.preload('/models/desk_set.glb')
export default Desk