/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Drifter-Models (https://sketchfab.com/Golden-Models)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/spotify-1b8c01e861604e6a9bdd390134546dea
Title: Spotify
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Sparkles } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
const SpotifyIcon=(props) =>{
  const { nodes, materials } = useGLTF('/models/spotify.glb')
  const ref=useRef()
  useFrame((state, delta) => {
 if (ref.current) {
      // DÜZELTME: İkonun dik eksende (Turntable gibi) dönmesi için Y yerine Z eksenini kullanıyoruz.
      ref.current.rotation.z += delta * 4; 
    }
  });
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, -Math.PI/2, 0]}
      position={[0,0,0]}>
        <group scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100,100, 13.486]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials['Material.001']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials['Material.004']}
            />
          </group>
        </group>
      </group>
            <Sparkles 
        count={50}          
        speed={1}           
        opacity={1}         
        scale={3}         
        size={7}            
        color={"#fff"}      
        noise={0.5}         
        position={[0,0, 0.05]} 
      />
    </group>
  )
}

useGLTF.preload('/models/spotify.glb')
export default SpotifyIcon