/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: StayLord (https://sketchfab.com/StayLord)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/target-26d9025cc9ba4377a343ea8d8a153100
Title: Target
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Target(props) {
  const { nodes, materials } = useGLTF('models/target.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['Material.001']}
        rotation={[0, 0, -1.445]}
        scale={[0.982, 0.044, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials['Material.002']}
        position={[-0.147, -0.889, -0.525]}
        rotation={[0.442, 0, 0]}
        scale={[0.079, 1, 0.079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials['Material.002']}
        position={[-0.147, -0.889, 0.496]}
        rotation={[2.692, 0, -Math.PI]}
        scale={[-0.079, 1, 0.079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials['Material.002']}
        position={[-0.5, -0.889, -0.029]}
        rotation={[-Math.PI, 0, -2.774]}
        scale={[-0.079, 1, 0.079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials['Material.002']}
        position={[-0.274, 0, -0.026]}
        scale={0.219}
      />
    </group>
  )
}

useGLTF.preload('models/target.glb')
export default Target